[package]
name = "ezk-session"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
ezk.workspace = true
ezk-rtp.workspace = true
sdp-types = { package = "ezk-sdp-types", version = "0.4" }
log = "0.4"
thiserror = "2"
rand = "0.8"
tokio = { version = "1", features = ["net"] }
